name: "My action"
description: "Test my action"

inputs:
  message:
    description: "The message to be displayed"
    required: true
    default: "Hello, World!"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo
      run: echo "Hola ${{ inputs.message }}"
      shell: bash